# NOTE: This file is a template and should be updated with the correct values
# before deploying to a Kubernetes cluster.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oliverrr-secret
data:
  ADMIN_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  DB_URI: c3VwZXItdG9wLXNlY3JldAo=
  JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
