name: Deploy Container Images

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'backend/**'
      - 'frontend/**'

env:
  image: thisoliver/oliverrr
  platforms: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # get code
      - name: Checkout
        uses: actions/checkout@v4

      # install jq to get the version from package.json
      - name: Install jq
        run: sudo apt-get install jq

      # get the version from package.json
      - name: Get the version
        id: package_version
        run: echo "::set-output name=version::$(jq -r .version package.json)"
      
      # setup quemu to build for multiple architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # builds for multiple architectures and packages them into a single image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # login to docker hub (use token instead of password)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # tag and push the image
      - name: Deploy Backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          tags: ${{ env.image }}:backend
          platforms: ${{ env.platforms }}
          push: true

      - name: Deploy Frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          tags: ${{ env.image }}:frontend
          platforms: ${{ env.platforms }}
          push: true
